#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include "lfsrUtils.h"

//Test file do not upvoat

//Current writes out the fourier series for the sequence generated by taps 0x0018

//#define tapNum 32768
//#define tapNum 16384
#define tapNum 4096
#define range 63

int main()
{

  unsigned int i, j, k;

  FILE* outFile;
  char outString[256];

  unsigned short **seqTable;  //seqTable[taps][val] = sequence id containing val

  printSequencesAtTaps(02044, 03777, tapNum);

  seqTable = getAllSequences(tapNum);

  //print sample for sanity check

  for(i = 0; i < 8; ++i)
  {
    for(j = 0; j < 8; ++j)
    {
      printf("%4.4x\t", seqTable[i][j]);
    }
    printf("\n");
  }


  //Computer all series
/*
  float ***seriesTables;

  seriesTables = calloc(tapNum, sizeof(float**));

  for(i = 0; i < tapNum; ++i)
  {
    printf("\r%3.1f%%\t", 100*((float)i)/tapNum);
    seriesTables[i] = getSeriesAtTaps(seqTable[i], tapNum, range);
  }
  printf("\n");
*/

  float** testTable;

//  testTable = getSeriesAtTaps(seqTable[0x0021], tapNum, range);
  testTable = getSeriesAtTaps(seqTable[02044], tapNum, range);

  outFile = fopen("testTable.txt", "wb");

  printf("Writing %f sequences\n", testTable[0][0]);

  for(i = 1; i <= testTable[0][0]; ++i)
  {
    k = sprintf(outString, "%2.0f\t", testTable[i][0]);
    fwrite(outString, k, 1, outFile);

    for(j = 1; j <= range; ++j)
    {
      k = sprintf(outString, "%f\t", testTable[i][j]);
      fwrite(outString, k, 1, outFile);
    }

    k = sprintf(outString, "\n");
    fwrite(outString, k, 1, outFile);
  }

  fclose(outFile);


  return 0;

}







